# Generated by Django 3.2.9 on 2021-12-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
